# Generated by Django 5.2.9 on 2025-12-28 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_created_at_branch_created_by_branch_manager'),
        ('loans', '0003_loan_created_at_loan_created_by_loan_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='loanapplication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='repayment',
            options={'ordering': ['-payment_date']},
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_applications', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='payment_date',
            field=models.DateField(),
        ),
    ]
